---
all:
  children:
    k8s_masters:
      hosts:
        master-1:
          ansible_host: 10.122.10.49
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: server
          rke2_server_init: true
        master-2:
          ansible_host: 10.122.11.18
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: server
          rke2_server_init: false
        master-3:
          ansible_host: 10.122.12.216
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: server
          rke2_server_init: false
    
    k8s_workers:
      hosts:
        worker-1:
          ansible_host: 10.122.10.160
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: agent
        worker-2:
          ansible_host: 10.122.11.19
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: agent
        worker-3:
          ansible_host: 10.122.12.121
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          rke2_type: agent

  vars:
    ansible_python_interpreter: /usr/bin/python3
    rke2_server_ip: 10.122.10.49  # First master node serves as the initial server
    cluster_cidr: "10.42.0.0/16"
    service_cidr: "10.43.0.0/16"
    rke2_version: "v1.28.15+rke2r1"
    rke2_channel: "stable"
    rancher_hostname: "rancher.smartcorex.com"
