---
all:
  children:
    rke2_server:
      hosts:
        rke2-server:
          ansible_host: 10.122.10.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    k8s_masters:
      hosts:
        master-1:
          ansible_host: 10.122.10.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        master-2:
          ansible_host: 10.122.11.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        master-3:
          ansible_host: 10.122.12.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    k8s_workers:
      hosts:
        worker-1:
          ansible_host: 10.122.10.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        worker-2:
          ansible_host: 10.122.11.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        worker-3:
          ansible_host: 10.122.12.XXX  # Update with actual IP from terraform output
          ansible_user: ec2-user
          ansible_ssh_private_key_file: ~/.ssh/SMP-ANSIBLE.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  vars:
    ansible_python_interpreter: /usr/bin/python3
    rke2_server_ip: 10.122.10.XXX  # Update with RKE2 server IP from terraform output
    cluster_cidr: "10.42.0.0/16"
    service_cidr: "10.43.0.0/16"
    rke2_version: "v1.28.5+rke2r1"
    rke2_channel: "stable"
    rancher_hostname: "rancher.smartcorex.com"