---
- name: System Setup and Preparation for RKE2
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Remove any existing problematic RKE2 repositories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/yum.repos.d/rancher-rke2-1.28-stable.repo
        - /etc/yum.repos.d/rancher-rke2-stable.repo
        - /etc/yum.repos.d/rancher-rke2.repo
      ignore_errors: yes

    - name: Clean package cache and metadata
      shell: |
        yum clean all
        rm -rf /var/cache/yum/*
        yum makecache fast || true
      ignore_errors: yes
      
    - name: Update system packages (force skip problematic repos)
      shell: |
        yum update -y --skip-broken --disablerepo=rancher-* || true
      register: system_update
      ignore_errors: yes

    - name: Install essential packages (skip broken repos)
      shell: |
        yum install -y --skip-broken --disablerepo=rancher-* \
          curl wget tar unzip vim git iptables \
          container-selinux selinux-policy-base || true
      register: package_install
      ignore_errors: yes

    - name: Check if firewalld exists
      stat:
        path: /usr/lib/systemd/system/firewalld.service
      register: firewalld_service

    - name: Disable firewalld if it exists
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      when: firewalld_service.stat.exists
      ignore_errors: yes

    - name: Configure SELinux to permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Load required kernel modules
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: Configure kernel modules to load at boot
      copy:
        content: |
          br_netfilter
          overlay
        dest: /etc/modules-load.d/rke2.conf
        mode: '0644'

    - name: Configure sysctl parameters for Kubernetes
      copy:
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        dest: /etc/sysctl.d/99-kubernetes.conf
        mode: '0644'

    - name: Apply sysctl settings
      command: sysctl --system

    - name: Create RKE2 directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /etc/rancher/rke2
        - /var/lib/rancher/rke2
        - /usr/local/bin

    - name: Display system setup completion
      debug:
        msg:
          - "System setup completed for {{ inventory_hostname }}"
          - "Role: {{ 'RKE2-Master' if inventory_hostname in groups['k8s_masters'] else 'RKE2-Worker' }}"
          - "Node Type: {{ 'Primary Master (Initializer)' if (inventory_hostname in groups['k8s_masters'] and rke2_server_init | default(false)) else ('Additional Master' if inventory_hostname in groups['k8s_masters'] else 'Worker Node') }}"
          - "Kernel modules loaded: br_netfilter, overlay"
          - "SELinux: permissive"
          - "Firewall: disabled"
          - "Ready for RKE2 installation"
