---
# This playbook is now deprecated - RKE2 installation is handled by 02-rke2-cluster.yml
# This file is kept for backwards compatibility but should not be used

- name: Deprecated - RKE2 server installation moved to 02-rke2-cluster.yml
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Warning about deprecated playbook
      debug:
        msg: |
          WARNING: This playbook (02-rke2-server.yml) is deprecated.
          RKE2 installation is now handled by the unified cluster playbook:
          02-rke2-cluster.yml
          
          Old approach: Dedicated RKE2 server + masters joining as servers
          New approach: First master initializes cluster + additional masters join as servers
          
          Please update deploy-all.yml to use the new architecture.
