---
# This playbook is now deprecated - RKE2 installation is handled by 02-rke2-cluster.yml
# This file is kept for backwards compatibility

- name: Deprecated - RKE2 installation moved to 02-rke2-cluster.yml
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Warning about deprecated playbook
      debug:
        msg: |
          WARNING: This playbook (03-k8s-nodes.yml) is deprecated.
          RKE2 installation for both masters and workers is now handled by:
          02-rke2-cluster.yml
          
          Please use the new unified RKE2 cluster playbook instead.
          
          Old approach: Separate RKE2 server + masters joining as servers + workers as agents
          New approach: First master initializes cluster + other masters join as servers + workers as agents

