---
- name: Verify Complete RKE2 Cluster and Rancher Installation
  hosts: k8s_masters[0]
  become: yes
  gather_facts: no
  
  tasks:
    - name: Check all cluster nodes
      shell: |
        export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        /usr/local/bin/kubectl get nodes -o wide
      register: cluster_nodes
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Check system pods
      shell: |
        export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        /usr/local/bin/kubectl get pods -A | grep -E "(kube-system|cattle-system|cert-manager)"
      register: system_pods
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      ignore_errors: yes

    - name: Check Rancher service
      shell: |
        export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        /usr/local/bin/kubectl get svc -n cattle-system rancher
      register: rancher_service
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      ignore_errors: yes

    - name: Check ingress controllers
      shell: |
        export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
        /usr/local/bin/kubectl get pods -A | grep ingress
      register: ingress_controllers
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml
      ignore_errors: yes

    - name: Display complete cluster status
      debug:
        msg:
          - "================ RKE2 CLUSTER STATUS ================"
          - "Cluster Nodes:"
          - "{{ cluster_nodes.stdout_lines }}"
          - ""
          - "System Pods:"
          - "{{ system_pods.stdout_lines | default(['No system pods found']) }}"
          - ""
          - "Rancher Service:"
          - "{{ rancher_service.stdout_lines | default(['Rancher service not found']) }}"
          - ""
          - "Ingress Controllers:"
          - "{{ ingress_controllers.stdout_lines | default(['No ingress controllers found']) }}"
          - ""
          - "================ ACCESS INFORMATION ================"
          - "RKE2 Server: {{ ansible_default_ipv4.address }}"
          - "Rancher URL: https://{{ rancher_hostname }}"
          - "Kubeconfig: /etc/rancher/rke2/rke2.yaml"
          - "kubectl: /usr/local/bin/kubectl"
          - ""
          - "Next Steps:"
          - "1. Configure ALB target group to point to Kubernetes masters"
          - "2. Access Rancher at https://{{ rancher_hostname }}"
          - "3. Complete Rancher initial setup"
          - "=================================================="

- name: Check individual node status
  hosts: k8s_masters,k8s_workers
  become: yes
  gather_facts: no
  
  tasks:
    - name: Check node service status
      shell: systemctl is-active {{ 'rke2-server' if inventory_hostname in groups['k8s_masters'] else 'rke2-agent' }}
      register: node_service_status
      ignore_errors: yes

    - name: Display node status
      debug:
        msg:
          - "Node: {{ inventory_hostname }}"
          - "Type: {{ 'Kubernetes Master' if inventory_hostname in groups['k8s_masters'] else 'Kubernetes Worker' }}"
          - "Service Status: {{ node_service_status.stdout | default('unknown') }}"
          - "Service: {{ 'rke2-server' if inventory_hostname in groups['k8s_masters'] else 'rke2-agent' }}"
