---
# RKE2 Kubernetes Cluster Deployment
# Automated deployment of production-ready RKE2 cluster with unified master architecture
# 
# New Architecture (Updated January 31, 2025):
# - 3 Kubernetes Masters with RKE2 (control plane) - 10.122.10.76, 10.122.11.172, 10.122.12.175
# - 3 Kubernetes Workers (data plane) - 10.122.10.159, 10.122.11.249, 10.122.12.215
# - First master (10.122.10.76) initializes the cluster, others join as additional servers
#
# After completion, use RANCHER-MANUAL-SETUP.md for manual Rancher installation

- name: System Preparation
  import_playbook: playbooks/01-system-setup.yml

- name: RKE2 Cluster Installation (Unified Single Playbook)
  import_playbook: playbooks/02-rke2-unified.yml

- name: ALB and Ingress Setup
  import_playbook: playbooks/04-alb-setup.yml

- name: Cluster Verification
  import_playbook: playbooks/05-cluster-verify.yml
